default: &default
  adapter: mysql2
  encoding: utf8
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: shubham
  password: Shubham@w3villa
  # socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: fb_development